"""recreate tables

Revision ID: 7e9273334c90
Revises: e44489471b1b
Create Date: 2023-09-08 17:31:16.083328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e9273334c90'
down_revision = 'e44489471b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_id', sa.Integer(), nullable=True),
    sa.Column('project_name_eng', sa.String(length=50), nullable=False),
    sa.Column('project_name_kor', sa.String(length=50), nullable=False),
    sa.Column('project_main_type_eng', sa.String(length=50), nullable=False),
    sa.Column('project_main_type_kor', sa.String(length=50), nullable=False),
    sa.Column('project_sub_type_eng', sa.String(length=50), nullable=False),
    sa.Column('project_sub_type_kor', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('no_of_team_members', sa.Integer(), nullable=False),
    sa.Column('team_name_eng', sa.String(length=50), nullable=False),
    sa.Column('team_name_kor', sa.String(length=50), nullable=False),
    sa.Column('summary_eng', sa.Text(), nullable=False),
    sa.Column('summary_kor', sa.Text(), nullable=False),
    sa.Column('role_description_eng', sa.Text(), nullable=False),
    sa.Column('role_description_kor', sa.Text(), nullable=False),
    sa.Column('issue_description_eng', sa.Text(), nullable=False),
    sa.Column('issue_description_kor', sa.Text(), nullable=False),
    sa.Column('project_link', sa.String(length=50), nullable=True),
    sa.Column('code_link', sa.String(length=50), nullable=True),
    sa.Column('project_image', sa.String(length=50), nullable=True),
    sa.Column('basic_info_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['basic_info_id'], ['basic_info.id'], ),
    sa.ForeignKeyConstraint(['career_id'], ['career.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_skill')
    op.drop_table('project')
    # ### end Alembic commands ###
