"""Initial migration

Revision ID: c05d29816bab
Revises: 
Create Date: 2023-09-08 15:30:34.011199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c05d29816bab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('career_project')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('career_id', sa.Integer(), nullable=True))
        batch_op.alter_column('project_link',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('code_link',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('project_image',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.create_foreign_key(None, 'career', ['career_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('project_image',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('code_link',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('project_link',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('career_id')

    op.create_table('career_project',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('career_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['career.id'], name='career_project_career_id_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='career_project_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='career_project_pkey')
    )
    # ### end Alembic commands ###
