"""recreate tables

Revision ID: e44489471b1b
Revises: c05d29816bab
Create Date: 2023-09-08 16:22:23.933894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e44489471b1b'
down_revision = 'c05d29816bab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_id', sa.Integer(), nullable=True),
    sa.Column('project_name_eng', sa.String(length=50), nullable=False),
    sa.Column('project_name_kor', sa.String(length=50), nullable=False),
    sa.Column('project_main_type_eng', sa.String(length=50), nullable=False),
    sa.Column('project_main_type_kor', sa.String(length=50), nullable=False),
    sa.Column('project_sub_type_eng', sa.String(length=50), nullable=False),
    sa.Column('project_sub_type_kor', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('no_of_team_members', sa.Integer(), nullable=False),
    sa.Column('team_name_eng', sa.String(length=50), nullable=False),
    sa.Column('team_name_kor', sa.String(length=50), nullable=False),
    sa.Column('summary_eng', sa.Text(), nullable=False),
    sa.Column('summary_kor', sa.Text(), nullable=False),
    sa.Column('role_description_eng', sa.Text(), nullable=False),
    sa.Column('role_description_kor', sa.Text(), nullable=False),
    sa.Column('issue_description_eng', sa.Text(), nullable=False),
    sa.Column('issue_description_kor', sa.Text(), nullable=False),
    sa.Column('project_link', sa.String(length=50), nullable=True),
    sa.Column('code_link', sa.String(length=50), nullable=True),
    sa.Column('project_image', sa.String(length=50), nullable=True),
    sa.Column('basic_info_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['basic_info_id'], ['basic_info.id'], ),
    sa.ForeignKeyConstraint(['career_id'], ['career.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_skill', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_skill', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('project')
    # ### end Alembic commands ###
